"use client";
import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "./ui/font";
import "swiper/swiper-bundle.css";
import Nav from "../../components/Nav";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
const metadata: Metadata = {
    title: "Flawless",
    description: "Generated by create next app",
};
import RouteChangeHandler from "../../components/RouteChangeHandler";
import Footer from "../../components/pages/Footer";
import store from "../../redux/store";
import { Provider } from "react-redux";
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const queryClient = new QueryClient({
        defaultOptions: {
            queries: {
                staleTime: 1000 * 60 * 5,
                gcTime: 2000 * 60 * 5,
                refetchOnWindowFocus: false,
            },
        },
    });
    return (
        <html lang="en">
            <body
                className={`${poppins.className} bg-primaryColor  antialiased`}
            >
                <QueryClientProvider client={queryClient}>
                    <Provider store={store}>
                        <RouteChangeHandler>
                            <Nav />
                            {children}
                            <Footer />
                        </RouteChangeHandler>
                    </Provider>
                </QueryClientProvider>
            </body>
        </html>
    );
}
